{% set name = "reedsolo" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1359f02742751afe0f1c0de9f0772cc113835aa2855d2db420ea24393c87732

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - reedsolo

about:
  home: https://github.com/tomerfiliba/reedsolomon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure-Python Reed Solomon encoder/decoder
  dev_url: https://github.com/tomerfiliba/reedsolomon

extra:
  recipe-maintainers:
    - m-rossi
